# Generated by Django 5.0.1 on 2024-01-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                ("table", models.TextField(verbose_name="Таблица")),
                (
                    "img",
                    models.ImageField(upload_to="geography/img", verbose_name="График"),
                ),
            ],
            options={
                "verbose_name": "География",
                "verbose_name_plural": "Географии",
            },
        ),
        migrations.CreateModel(
            name="Relevance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                ("table", models.TextField(verbose_name="Таблица")),
                (
                    "img",
                    models.ImageField(upload_to="relevance/img", verbose_name="График"),
                ),
            ],
            options={
                "verbose_name": "Востребованность",
                "verbose_name_plural": "Востребованности",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Название")),
                ("table", models.TextField(verbose_name="Таблица")),
                (
                    "img",
                    models.ImageField(upload_to="skills/img", verbose_name="График"),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
    ]
